### ISSUE TITLE
Cmake error: ModuleNotFoundError: No module named 'skbuild'

### ISSUE THREAD

**Issue by armunday** [scikit-build/cmake-python-distributions#103]
I have been troubleshooting this error for a day and a half now to no avail. Not sure what is going on. I saw a solved issue but those fixes are not working for me. Below is the error code.

```
Collecting line_profiler
  Using cached line_profiler-3.0.2.tar.gz (45 kB)
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\DisasterConsult\COVID-19-Disaster-Consult\venv\Scripts\python.exe' 'C:\DisasterConsult\COVID-19-Disaster-Consult\venv\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\12066\AppData\Local\Temp\pip-build-env-yt9ionzt\overlay' --no-warn-script-location --no-binary :all: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=41.0.1' wheel Cython 'scikit-build>=0.9.0' cmake ninja
       cwd: None
  Complete output (21 lines):
  Collecting setuptools>=41.0.1
    Using cached setuptools-47.1.0.zip (870 kB)
  Collecting wheel
    Using cached wheel-0.34.2.tar.gz (58 kB)
  Collecting Cython
    Using cached Cython-0.29.19.tar.gz (2.1 MB)
  Collecting scikit-build>=0.9.0
    Using cached scikit-build-0.11.1.tar.gz (132 kB)
  Collecting cmake
    Using cached cmake-3.17.2.tar.gz (28 kB)
      ERROR: Command errored out with exit status 1:
       command: 'C:\DisasterConsult\COVID-19-Disaster-Consult\venv\Scripts\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\12066\\AppData\\Local\\Temp\\pip-install-lbq2lcg6\\cmake\\setup.py'"'"'; __file__='"'"'C:\\Users\\12066\\AppData\\Local\\Temp\\pip-install-lbq2lcg6\\cmake\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\12066\AppData\Local\Temp\pip-pip-egg-info-9b0a6ibk'
           cwd: C:\Users\12066\AppData\Local\Temp\pip-install-lbq2lcg6\cmake\
      Complete output (5 lines):
      Traceback (most recent call last):
        File "<string>", line 1, in <module>
        File "C:\Users\12066\AppData\Local\Temp\pip-install-lbq2lcg6\cmake\setup.py", line 7, in <module>
          from skbuild import setup
      ModuleNotFoundError: No module named 'skbuild'
      ----------------------------------------
  ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\DisasterConsult\COVID-19-Disaster-Consult\venv\Scripts\python.exe' 'C:\DisasterConsult\COVID-19-Disaster-Consult\venv\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\12066\AppData\Local\Temp\pip-build-env-yt9ionzt\overlay' --no-warn-script-location --no-binary :all: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=41.0.1' wheel Cython 'scikit-build>=0.9.0' cmake ninja Check the logs for full command output.
```

**Comment by armunday** [comment]
I have C++ Build Tools installed, I have cmake installed and it is in my environment variables. Just have no clue what is happening

**Comment by jcfr** [comment]
It looks like you are installing the `line_profiler` package (either directly or indirectly by installing an other package having `line_profiler` as a dependency)

As we can see [here](https://pypi.org/project/line-profiler/#files), the latest version of `line_profiler` do not provide window wheels (file with the `.whl` extension). 

A wheel is a convenient "archive" containing everything ready to be installed for the current platform.

Considering there are no convenient `.whl` file for windows, python try to **build** the wheel locally before installing it. 

For some reason, on your platform .. it also tries to build cmake wheel from source. Which is strange because, we provide wheel for windows. See https://pypi.org/project/cmake/#files

We can see [here](https://github.com/pyutils/line_profiler/blob/a04473eb4bd96f8b17461cb17c94ea4ad65a9a8a/setup.py#L270) the build time dependencies. 

For convenience, here is the content of [requirements/build.txt ](https://github.com/pyutils/line_profiler/blob/master/requirements/build.txt ):

```
Cython
scikit-build
cmake
ninja
```

**Comment by jcfr** [comment]
What happen if you run the following:

```
python --version
```

```
python -m pip install cmake
```

**Comment by henryiii** [comment]
Can you try updating pip (should be trivial in the virtual environment, and if that doesn't work by itself, with `--prefer-binary`? Also try purging your cache, just in case. I see a `--no-binary :all: --only-binary :none:` which sounds like it is turning off all binaries.

**Comment by henryiii** [comment]
This would be very much improved if there was a `pyproject.toml` file. Then you might fail due to missing system libraries, but not due to "scikit-build" missing. Currently, inside a `pyproject.toml` file including cmake, it is _impossible_ to build from source, since it creates a temporary virtual environment for building with just the items listed in this file, and then when trying to build cmake, scikit-build is not available (in the new, temporary environment), so it doesn't work.

**Comment by skvark** [comment]
I would also recommend to add `pyproject.toml` to this project. For example, this case could have been avoided with `pyproject.toml`: https://github.com/skvark/opencv-python/issues/387#issuecomment-703237990

**Comment by jcfr** [comment]
> I would also recommend to add pyproject.toml to this project. For example, this case could have been avoided with pyproject.toml

@skvark : 
* Arm64 wheel should be available in the next 30mins or so
* we also added `pyproject.toml` (thanks @yoav-orca for the contribution) 
* I created an issue so that we update the build system to display a warning when the wheel is built from source as this should be reported so that we can add support for distributing the corresponding wheel.

**Comment by skvark** [comment]
Thanks!

**Comment by henryiii** [comment]
This should be solved now!

**Comment by henryiii** [comment]
(Where now might mean some time ago, or with the 3.20.2 release)
