### ISSUE TITLE
cibuildwheel for Continous Deployment

### ISSUE THREAD

**Issue by ax3l** [scikit-build/cmake-python-distributions#138]
Hi @jcfr and @henryiii,

after a few earlier attempts to widen the binary wheel support for urgently needed platforms such as `aarch64` #96 #134 #132 and `ppc64le`, I took a try at it using @joerick's fantastic [cibuildwheels](https://github.com/joerick/cibuildwheel) project.

You can see my efforts and rationale here: https://github.com/ax3l/cmake-cibuildwheel

Is there general interest to move forward with this?

Personally, I quite urgently (actually since the inauguration of Summit at OLCF three years ago) need `ppc64le` wheels for users on pre-Exascale supercomputers and Linux `aarch64` HPC machines are also there now alongside cloud machines :)

**Comment by henryiii** [comment]
I believe the next release will have support for these platforms, due to @mayeut's fantastic PRs. I think we are just waiting for @jcfr to push the button (and maybe trying to get a few last bits in, like #137). I'd love to use GHA and cibuildwheel in the future, but personally have been short on time to set it up. If you could help with it, I believe it would be very much appreciated (@jcfr can verify).

**Comment by ax3l** [comment]
Oh that's awesome, I'll wait for the final touches then and leave the repo around for now. Great news!

I'm reporting in the meantime some upstream issues, e.g. this macOS `delocate` issue: https://github.com/matthew-brett/delocate/issues/105

**Comment by henryiii** [comment]
Xref: https://github.com/scikit-build/scikit-build/issues/507

**Comment by mayeut** [comment]
@ax3l,

I like the idea very much. So much that I opened a draft PR to start working on this !
