### ISSUE TITLE
Switch from versioneer to pypa/setuptools_scm

### ISSUE THREAD

**Issue by jcfr** [scikit-build/cmake-python-distributions#143]
Would it be a good idea to move to pypa/setuptools_scm? It has nice tooling for this sort of thing; the manual versioner script doesn't have the nice overrides.

_Originally posted by @henryiii in https://github.com/scikit-build/cmake-python-distributions/issues/141#issuecomment-845240054_

----

> We are currently versioneer, which problem would setuptools_scm address ?

Two problems. One is we have a lot of custom code (including `versioneer.py` and various workarounds), while setuptools_scm simply is a PyPI package. Second, with setuptools_scm, there are environment variable overrides (specifically, I needed `SETUPTOOLS_SCM_PRETEND_VERSION`) that can be used for emergency operations like this one. Also, it's a PyPA standard package instead of custom code.

_Originally posted by @henryiii in https://github.com/scikit-build/cmake-python-distributions/issues/141#issuecomment-845254006_

**Comment by henryiii** [comment]
Was just about to open this. :) For reference:

> We are currently versioneer, which problem would setuptools_scm address ?

Two problems. One is we have a lot of custom code (including versioneer.py and various workarounds), while setuptools_scm simply is a PyPI package. Second, with setuptools_scm, there are environment variable overrides (specifically, I needed SETUPTOOLS_SCM_PRETEND_VERSION) that can be used for emergency operations like this one. Also, it's a PyPA standard package instead of custom code.

**Comment by mayeut** [comment]
I tried moving to pypa/setuptools_scm but something went wrong with the MANIFEST for sdist at least (nox failing there).
It might be related to https://github.com/scikit-build/scikit-build/pull/402 (or not), needs further investigation.
