### ISSUE TITLE
Issue building on AppVeyor

### ISSUE THREAD

**Issue by henryiii** [scikit-build/cmake-python-distributions#24]
The recent AppVeyor builds fail with `from setuptools import monkey` on Python 3.3. and 3.4. I think a reasonable solution would be to drop these from the build, and then rename the output to a general version for all pythons (asked for for 3.6 support). So both issues could potentially be solved at the same time.

**Comment by henryiii** [comment]
@jcfr, does the upload to Pypi use CI artifacts? I think renaming the resulting wheel might work, but I'm not sure where to add that step. I think (if setup tools is like the wheel package) that it will ignore version independent flags if there is a C extension, but manually renaming the files might work.

**Comment by jcfr** [comment]
Hi @henryiii , sorry for the later reply. Thanks again for investigative work.

I will be looking at this now to fix scikit-build so that the issue with 3.3 and 3.4 are addressed.

> then rename the output to a general version for all pythons

@blowekamp looked at this , but it seems it is not possible. See https://github.com/scikit-build/cmake-python-distributions/issues/18#issuecomment-295397820

> use CI artifacts?

We currently upload all wheels to a staging area. See [scikit-ci.yml#L59-L69](https://github.com/scikit-build/cmake-python-distributions/blob/5a4faaa54c0b2f74ceaadde5efb4d3f24d0308c1/scikit-ci.yml#L59-L69) and http://cmake-python-distributions.readthedocs.io/en/latest/make_a_release.html

Soon we will transition to directly upload as GitHub release using http://scikit-ci-addons.readthedocs.io/en/latest/addons.html#publish-github-release-py

**Comment by jcfr** [comment]
Closing. This is now fixed by #21
