### ISSUE TITLE
CMake version 3.26.4 is unavailable in pip

### ISSUE THREAD

**Issue by karanshah** [scikit-build/cmake-python-distributions#371]
Hello! CMake has released 3.26.4 version, but is not available via pip. Can this version be added to pip?

**Comment by jcfr** [comment]
For reference:
* https://github.com/scikit-build/cmake-python-distributions/pull/365

**Comment by jcfr** [comment]
@henryiii @mayeut Since the CI run [^1] associated with #365 was :heavy_check_mark:

Any objection if tag `v3.36.4` ?

[^1]: https://github.com/scikit-build/cmake-python-distributions/actions/runs/5019944234

**Comment by henryiii** [comment]
I think there's an issue with the Windows ARM wheels. I think the CMake inside the wheel is actually the wrong version, and just happens to work since Windows ARM can run x86 code via emulation. I'd like to fix that if possible first.

```
2023-05-19T02:02:07.9979465Z   -- Downloading...
2023-05-19T02:02:07.9980442Z      dst='D:/a/cmake-python-distributions/cmake-python-distributions/_skbuild/win-amd64-3.9/cmake-build/cmake-3.26.4-windows-i386.zip'
2023-05-19T02:02:07.9997851Z      timeout='none'
2023-05-19T02:02:08.0001737Z      inactivity timeout='none'
2023-05-19T02:02:08.0003023Z   -- Using src='https://github.com/Kitware/CMake/releases/download/v3.26.4/cmake-3.26.4-windows-i386.zip'
```

**Comment by jcfr** [comment]
I gonna have a look this afternoon

**Comment by henryiii** [comment]
Okay, great, it's probably just a case of fixing the download script to grab the right one.

I've also been working on Windows ARM at https://github.com/wjakob/nanobind_example/pull/27 and have been working on the horror that is https://github.com/scikit-build/scikit-build-core/pull/355 to support it, since FindPython doesn't seem to support setting `Python_SOABI` as input, which is necessary for cross-compilation (and could save a subprocess call even if not cross compiling). Setuptools supports overriding via the environment variable `SETUPTOOLS_EXT_SUFFIX`.

But all of this won't affect cmake/ninja, since they are not making Python extensions.

I might try to propose something in the future.

**Comment by jcfr** [comment]
> just a case of fixing the download script to grab the right one.

Ditto. Once linked pull request completes, we should be able to tag `v3.26.4`

**Comment by jcfr** [comment]
`3.26.4` has been published[^1], wheels will be uploaded shortly.

[^1]: https://github.com/scikit-build/cmake-python-distributions/releases/tag/3.26.4

**Comment by jcfr** [comment]
I thought one of the job was "stuck" as it has been running for ~3hrs ... but looking at the log of `3.26.3`, the timing is consistent.

| `3.26.3` :heavy_check_mark:  | `3.6.24` :hourglass_flowing_sand: |
|--|--|
| ![image](https://github.com/scikit-build/cmake-python-distributions/assets/219043/0e904ddb-0549-49d2-9150-346b6c81ccac) | ![image](https://github.com/scikit-build/cmake-python-distributions/assets/219043/30d2db24-d324-4f5d-8b3a-53a6a541a43a) |

**Comment by jcfr** [comment]
And here is a break down of the timing (from `3.26.3` log[^1]):

![image](https://github.com/scikit-build/cmake-python-distributions/assets/219043/65c14681-4916-4b46-9c9f-12b9d11995f3)

[^1]: https://github.com/scikit-build/cmake-python-distributions/actions/runs/4658536917/jobs/8244345614#step:4:93

**Comment by jcfr** [comment]
Wheels for `3.26.4` are now available. See https://pypi.org/project/cmake/3.26.4/
