### ISSUE TITLE
Python 3.7 wheels release

### ISSUE THREAD

**Issue by YannickJadoul** [scikit-build/cmake-python-distributions#42]
Is there any prospect of having Python 3.7 wheels released soon enough?
I am using this project to install CMake within the manylinux docker image to build my own project. As I was updating that setup to now build 3.7 wheels, I get an error (because the source distribution is trying to get installed, instead of the 3.7 wheel).

But I do notice that Python 3.7 wheels are already being built by CircleCI, for this project?

Thanks a lot for these CMake wheels, by the way; so much easier to quickly install CMake! :-)

**Comment by jcfr** [comment]
Hi @YannickJadoul , 

Yes, just back from SciPy conference and having done a new new a release of [scikit-build](https://pypi.org/project/scikit-build/), we will release a new wheels for ninja and cmake shorlty. 

First, we will update their build system so that it directly upload wheels to pypa after a tag is pushed. (Currently, wheels are uploaded into a staging area first, then they have to be downloaded, and uploaded explicitly. This was done so that we can sign them. That said, since signing wheels was partially supported and was giving a false sense of confidence ... we will skip this moving forward)

**Comment by YannickJadoul** [comment]
@jcfr Nice. Thanks a lot! :-)
If you would need a helping hand, I'd be happy to help out a bit where I can.

**Comment by YannickJadoul** [comment]
Great, thank you!
