### ISSUE TITLE
3.14, "Problem with the CMake installation, aborting build"

### ISSUE THREAD

**Issue by achaikou** [scikit-build/cmake-python-distributions#76]
Might be related to #60 and mentioned PR

Before 3.14:
_python -m pip install cmake pybind11 scikit-build_
worked fine

With 3.14:
_ImportError: No module named 'skbuild'_
Full log:
https://travis-ci.org/equinor/dlisio/jobs/537728246

Changed installation order:
_python -m pip install scikit-build
python -m pip install cmake_

File "/opt/python/cp35-cp35m/lib/python3.5/site-packages/skbuild/cmaker.py", line 81, in get_cmake_version
Problem with the CMake installation, aborting build. CMake executable is cmake
Full log:
https://travis-ci.org/equinor/dlisio/jobs/537745800

**Comment by jcfr** [comment]
Starting with CMake 3.14.3, manylinux2010 is used to build the wheel ... and since manylinux1 is used by multibuild, the `pip install cmake` command decide it should build cmake from source. 

Waiting this addressed in multibuild, I submitted a PR to "work around" the issue.

I think this might be a pip issue, it should not decide to build the project from source right way and instead look if older version are compatible.

**Comment by jcfr** [comment]
An issue has been reported in upstream, see https://github.com/pypa/pip/issues/6547

**Comment by kanamadiharshita** [comment]
cmake version 3.29 python3.12 llama-cpp-python=0.2.57
i am getting error ValueError: Model path does not exist: mistral-7b-instruct-v0.1.Q4_K_M.gguf
